### ISSUE TITLE
Syntax highlighting på kodeblokker

### ISSUE THREAD

**Issue by OIex** [iterate/mikrobloggeriet#111]
For å bedre lese artikler som [denne](https://mikrobloggeriet.no/iterate/iterate-2/) hadde det vært supert med syntax highlightin på kodeblokker sånn som feks Github har. Uten det ble det egentlig lettere å [lese innlegget på github](https://github.com/iterate/mikrobloggeriet/blob/master/text/iterate/iterate-2/index.md) enn mikrobloggeriet

**Comment by olavm** [comment]
Done!
