### ISSUE TITLE
Redirect av gamle olorm-URL'er

### ISSUE THREAD

**Issue by olavm** [iterate/mikrobloggeriet#19]
Siste build av det gamle [olorm-repoet](https://github.com/iterate/olorm) kjører fortsatt på [Iterapp](https://apps.iterapp.no/apps/iterate/olorm). Det siste buildet fra olorm-repoet før prosjektet be archived, og utvikling gikk over til [mikrobloggeriet repoet](https://github.com/iterate/mikrobloggeriet/) er fortsatt live på https://serve.olorm.app.iterate.no/. Blogginnlegg lever fortsatt under eksempelvis https://serve.olorm.app.iterate.no/o/olorm-6/.

Her er det flere problemer som bør adresseres:

1. Hva skal vi gjøre med de gamle URL-ene? Skal den gamle nettsiden få fortsette å leve, og skal brukere ha mulighet til å navigere rundt i et eldre snapshot av mikrobloggeriet? Skal vi gå inn å endre, slik at hver gamle lenke redirecter til tilsvarende artikkel på https://mikrobloggeriet.no/?
2. Har HOPS-teamet noen meninger rundt archived prosjekter, og prosjekter som blir flyttet til nye repo? Er det noen kostnader tilknyttet å holde olorm i live på Iterapp?

**Comment by teodorlu** [comment]
Jeg ser tre muligheter:

1. Slette det gamle, drite i bakoverkompatibilitet
2. La den gamle appen fortsette å kjøre, men endre den så man får permanent redirects for de gamle url-ene
3. Sørge for redirects uten å ha den gamle appen kjørende.

Nr 1 mener jeg er feil å gjøre, bakoverkompatibilitet er viktig.

Nr 2 er ganske lett og rett fram. Vi endrer koden til å lage HTTP permant redirects til mikrobloggeriet.no.

Nr 3 gir fordelene med nr 2, men er lettere å vedlikeholde. Kanskje HOPS kan tilby noe for dette. Skal vi kjøre det selv, tror jeg vi kan skrive en Nginx-config. Nr 3 er litt mer "riktig verktøy for jobben" enn 2. Da kam Vi også beholde repoet fungerende sånn det er, arkivert.

Mer om nginx redirects: https://stackoverflow.com/questions/10294481/how-to-redirect-a-url-in-nginx

Mange folk kan nginx i Iterate. Jeg ville spurt Richard, Sindre, Oddmund eller Marcus.

**Comment by teodorlu** [comment]
> Har HOPS-teamet noen meninger rundt archived prosjekter, og prosjekter som blir flyttet til nye repo? Er det noen kostnader tilknyttet å holde olorm i live på Iterapp?

Hadde vært veldig fint å vite cirka antall kroner per måned det koster å kjøre denne appen, ja. Jeg mener generelt vi bør vite mer om hva infrastrukturen vår koster.
