### ISSUE TITLE
Når `mblog create` kjøres utenfor repo-mappen, lages `index.md` og `meta.edn` i feil mappe

### ISSUE THREAD

**Issue by teodorlu** [iterate/mikrobloggeriet#32]
`olorm` og `jals`-cliene kan kjøres fra alle mapper på brukerens PC. Det senker terskelen for å skrive. Åpne en terminal, kjør `jals create`, done.

Med `mblog create` ser det ut som CLI-et lager `index.md` og `meta.edn` utenfor repoet:

```
$ pwd                
/Users/teodorlu/tmp/temp-2023-08-31
$ mblog create --dry-run
[:shell {:dir "/Users/teodorlu/dev/iterate/mikrobloggeriet"} "git pull --ff-only"]
[:create-dirs #object[java.io.File 0x349c9491 "o/olorm-1"]]
[:spit #object[java.io.File 0x6e2b4ff "o/olorm-1/index.md"] "# OLORM-1\n\n<!-- 1. Hva gjør du akkurat nå? -->\n\n<!-- 2. Finner du kvalitet i det? -->\n\n<!-- 3. Hvorfor / hvorfor ikke? -->\n\n<!-- 4. Call to action---hva ønsker du kommentarer på fra de som leser? -->"]
[:spit #object[java.io.File 0x565effc3 "o/olorm-1/meta.edn"] "{:git.user/email \"git@teod.eu\", :doc/created \"2023-08-31\", :doc/uuid \"dfa2ad09-353c-4bcd-859e-aa80d3b0dafb\"}\n"]
[:shell {:dir "/Users/teodorlu/dev/iterate/mikrobloggeriet"} "emacs" #object[java.io.File 0x52ae2c30 "o/olorm-1/index.md"]]
[:shell {:dir "/Users/teodorlu/dev/iterate/mikrobloggeriet"} "git add ."]
[:shell {:dir "/Users/teodorlu/dev/iterate/mikrobloggeriet"} "git commit -m" "olorm-1"]
[:shell {:dir "/Users/teodorlu/dev/iterate/mikrobloggeriet"} "git pull --rebase"]
[:shell {:dir "/Users/teodorlu/dev/iterate/mikrobloggeriet"} "git push"]
[:println "Husk å publisere i #mikrobloggeriet-announce på Slack. Feks:\n\n   OLORM-1: $DIN_TITTEL → https://mikrobloggeriet.no/olorm/olorm-1/"]
```

Med andre ord, for å reprodusere:

1. Gå til en annen mappe enn repoet
3. Kjør `mblog create --dry-run`.

Expected: `:spit` og `:create-dirs`-kommandoer tar hensyn til `repo-path`. 

Actual: `:spit` og `:create-dirs` kjøres relativt til brukerens _nåværende_ mappe.

**Comment by teodorlu** [comment]
Mulig denne rett og slett er litt vanskelig å fikse.

I gamle dager hadde `olorm`-er og `jals`-er i `olorm.clj` og `jals.clj` et `repo-path`-felt de drev og sendte rundt. Det droppet jeg å ta med da jeg startet med `store`, `doc` og `cohort`.

Men nå har vi laget funksjoner i `store` som leser og skriver filer! De funksjonene trenger å vite _hvor_ de skal lese og skrive filer.

**Comment by teodorlu** [comment]
Mulig løsning:

- Legge på et optional `repo-path`-felt på kohorter
- Setter og getter i `repo-path`
- Defaultverdi er "." (mappen du er i)

Så kan `mikrobloggeriet.cli` sørge for å sette `repo-path` korrekt etter config.

Dette krever i tilfelle endringer i en del funksjoner i `store` - som må ta hensyn til at roten ikke nødvendigvis er "." for å hente ut feks filsti for metadata-fil eller markdown-fil.

**Comment by olavm** [comment]
Fikset i #33
