### ISSUE TITLE
Opsjon: kohort for å snakke om generativ ai (`:genai`)

### ISSUE THREAD

**Issue by teodorlu** [iterate/mikrobloggeriet#4]

**Comment by teodorlu** [comment]
Status:

* Oppsettet for kohorten er helt klart
* Men vi har ikke noe innhold, eller noen som har sagt ja til å skrive.

**Comment by jraregris** [comment]
Ville det ikke vært på sin plass å la ChatGPT et al ta seg av skrivingen her?

**Comment by teodorlu** [comment]
Det kunne vært kullt!

Men da mener jeg det bør framkomme tydelig i GUI at teksten folk leser er AI-generert.

**Comment by teodorlu** [comment]
Foreslår at vi lukker denne:

1. Jeg fikk ikke noe svar i #genai da jeg spurte om noen ville skrive
2. Julian ser ikke ut til å være _så_ interessert i å bruke CLI-et (forståelig)

Så hvorfor lukke?

1. Vi kan slette død kode på master
2. Vi kan lukke denne diskusjonen
3. Det er kjempelett å lage en ny kohort nå hvis vi ønsker; få til tilbake genai er ikke store jobben.
