### ISSUE TITLE
Opsjon: måling av trafikk på ulike sider på mikrobloggeriet

### ISSUE THREAD

**Issue by olavm** [iterate/mikrobloggeriet#59]
Neno har ønsket seg dette. Mange måter til målet. Hvor lite sporing må en session cookie ha slik at vi ikke trenger å ha cookie samtykke banner? Mange spørsmål!

**Comment by teodorlu** [comment]
Dette hadde vært dritkult å vite mer om! Synes også problemet er spennende.

**Comment by teodorlu** [comment]
Nå som vi er på Garden er dette lettere enn vi skulle trodd.

En mulig løsning er map fra dag og uri til count i et durable atom (duratom, https://github.com/jimpil/duratom).

Noe sånt:

```
{["/urlog/" "2024-12-22"] 22}
```

22 besøkende på URLOG på dagens dato.

**Comment by teodorlu** [comment]
@nenomindjek @olavm nå måler vi trafikk!

https://mikrobloggeriet.no/analyse/

Jeg har skrudd på måling for alle sider, men det er opt-inn hva vi viser på analysesiden.
