### ISSUE TITLE
Installasjon av `mblog` krever mange steg

### ISSUE THREAD

**Issue by teodorlu** [iterate/mikrobloggeriet#60]
## Problem: vanskelig å installere CLI-et

I dag er det mange steg man må gjennom for å installere `mblog`-CLI-et fra en frisk PC. Hvis man aldri har jobbet med Clojure og Babashka før, må man bruke tid på å skjønne hva ting er. Mange av de som skriver på Mikrobloggeriet har aldri sett verken Clojure eller Babashka. I stedet for å installere CLI-et, sender de tekst på DM til Olav, så publiserer Olav.

## Homebrew

Hvis vi lager `brew install mikrobloggeriet`, tar det kortere tid fra 0 til action for publisering.

## Løsingsstrategi 1: frikoblet babashka-script, ingen kodedeling

Hvis CLI-et ikke deler noe kode med resten av mikrobloggeriet, kan CLI-er slippe avhengigheter, og blir lettere. Da tror jeg det holder med én fil babashka.

Problemer: uten kodedeling med resten av mikrobloggeriet må vi finne en annen måte å dele informasjon om kohorter. Kanskje det endelig er på tide å trekke den informasjonen ut i data?

```
cat mikrobloggeriet/cohorts.edn
... all infoen man trenger ...
```

## Løsningsstrategi 2: shippe eksisterende CLI-navnerom til Homebrew, sørge for at vi får installert alt av nødvendige avhengigheter.

Litt usikker på om vi kommer til å få denne til. Men hvis vi kan holde eksisterende CLI-navnerom urørt, kan vi beholde eksisterende arkitektur, og det er kjekt.

**Comment by teodorlu** [comment]
Jeg fikk til å lage en "self contained executable" til mac.

## Hvordan

```
$ bb uberjar mblog.jar -m mikrobloggeriet.cli
$ cat `which bb` mblog.jar > mblog-mac-binary
$ chmod +x ./mblog-mac-binary
```

Den kan da kjøres sånn:

```
$ ./mblog-mac-binary
Available subcommands:

  help
  config
  create
  urlog create
```

## Hva så?

Det er fremdeles noen ubesvarte spørsmål.

1. Hvordan håndterer vi forskjellige arkitekturer? Jeg kan lage et AARCH64-bygg. Hva med Linux? Hva med AMD64?
2. Hvordan skal en bruker installere binaryen? Manuelt fra Github releases?
3. Hvordan skal en bruker oppdatere binaryen?
4. Hvordan skal vi versjonere binaryen? Når vi shipper en binary, kommer den etter hvert til å bli gammel.

## Konklusjoner

1. Tror å lage `brew install mikrobloggeriet` (eller `brew install iterate/taps/mikrobloggeriet` eller hva det blir) fremdeles er beste mulighet. Det er hva folk er kjent med, og Homebrew har oppdatering innebygget.
2. Jeg har per i dag _ikke_ noen god løsning på CI. Såvidt jeg vet støtter ikke Github actions AARCH64.

**Comment by marcusirgens** [comment]
Til info: https://github.com/iterate/homebrew-tap

**Comment by teodorlu** [comment]
@tingstad gir en mulig løsning på dette i #74.

**Comment by teodorlu** [comment]
Jeg anser denne løst nå - siden vi har mblog.sh på master (#74)
