### ISSUE TITLE
Problem: CSS rendrer ikke skikkelig i Chrome

### ISSUE THREAD

**Issue by teodorlu** [iterate/mikrobloggeriet#79]
## Kontekst

HTML og CSS har blitt endret for å flytte stil til CSS, i stedet for å generere HTML.

Logikken ble flyttet til CSS i https://github.com/iterate/mikrobloggeriet/pull/64 og i https://github.com/iterate/mikrobloggeriet/commit/f2f10812300a95466e67d4d7f62da131b5191d15.

## Problem

Lenker vises feil i Chrome i produksjon nå:

![image](https://github.com/iterate/mikrobloggeriet/assets/5285452/fd1cbca4-b77c-4b59-8ced-db1807200c1c)

Bildene kommer under hverandre.

Hos meg fungerer det som det skal i Firefox, Chromium (!) og Safari:

<img width="1800" alt="image" src="https://github.com/iterate/mikrobloggeriet/assets/5285452/1988a4be-5481-4cbe-98a7-0bfed0382f5a">

**Comment by teodorlu** [comment]
Jeg prøvde å revertere de to committene, men vi får en merge-konflikt.

**Comment by teodorlu** [comment]
Jeg har utforsket litt bruk av playwright. Det funker bra. Men playwright støtter ikke å installere og kjøre chrome, kun chromium. Så vi ville faktisk _ikke_ funnet denne feilen selv med playwright-tester.

Her er et playwright-script:

```clojure
(ns learn.mikrobloggeriet-css-bug
  (:import (com.microsoft.playwright Playwright)
           com.microsoft.playwright.BrowserType$LaunchOptions))

;; reproduce https://github.com/iterate/mikrobloggeriet/issues/79 locally

(def m-local "http://localhost:7223")
(def m-prod "https://mikrobloggeriet.no")

(defonce playwright-instance (atom nil))
(defn init! []
  (when (nil? @playwright-instance)
    (reset! playwright-instance (Playwright/create))))

(defn halt! []
  (when-not (nil? @playwright-instance)
    (.close @playwright-instance)
    (reset! playwright-instance nil)))

(comment
  @playwright-instance

  (init!)
  (halt!)
  )

(defn init-pages [playwright]
  (let [browser-opts (-> (BrowserType$LaunchOptions.)
                         (.setHeadless false))
        browser-templates [(.firefox playwright)
                           (.chromium playwright)
                           (.webkit playwright)
                           ;; playwright does not have "safari", but webkit is similar
                           ]
        ]
    ;; return a browser _page_ for each (a tab)
    (doall
     (for [template browser-templates]
       (.newPage (.launch template browser-opts))))))

(defonce pages (atom nil))

(comment
  ;; start playwright
  (init!)
  ;; start a bunch of pages
  (reset! pages (init-pages @playwright-instance))
  (first @pages)

  (def m-local "http://localhost:7223")
  (def m-prod "https://mikrobloggeriet.no")
  (def m-olorm-1 "https://mikrobloggeriet.no/olorm/olorm-1/")

  (doseq [p @pages]
    (.navigate p (str m-prod "/o/olorm-1/")))

  (doseq [p @pages]
    (.navigate p (str m-local "/o/olorm-48/")))

  (doseq [p @pages]
    (.navigate p (str m-local "/luke/luke-7/")))

  )
```

Kjør `(init!)` i en REPL, så `(reset! pages (init-pages @playwright-instance))`. Deretter `doseq`-ene på slutten for å se på én URL i tre nettlesere.

Da får du noe sånt:

https://github.com/iterate/mikrobloggeriet/assets/5285452/ab4c5d6e-23e6-4a07-afb3-246e4b72eee1

**Comment by teodorlu** [comment]
Jeg oppgraderte nettopp fra Chrome 119 til Chrome 121. Nå får jeg hjemmeside med "ordentlig CSS".

![image](https://github.com/iterate/mikrobloggeriet/assets/5285452/93260832-c878-4025-8220-65df75480286)

**Comment by teodorlu** [comment]
@olavm @jraregris

Hva synes dere vi bør gjøre? Kjøre videre med sånn CSS/HTML er nå, eller gå tilbake til sånn det var før for å støtte eldre nettlesere?

Mikrobloggeriet er et verktøy for _oss som skriver_. Poenget fra starten har vært å gjøre det greit å skrive.

Samtidig er det jo fint at siden funker i typiske nettlesere folk bruker, og litt pinlig når stilen brekker.

**Comment by jraregris** [comment]
Fra _release notes_ for Chrome 120

<img width="869" alt="image" src="https://github.com/iterate/mikrobloggeriet/assets/37021/16221b26-ef56-46ef-8390-b3b91968f990">
