### ISSUE TITLE
Opsjon: endepunkt for å trekke nye innlegg (feks `/olorm/draw/ol` og `/jals/draw/als`)

### ISSUE THREAD

**Issue by teodorlu** [iterate/mikrobloggeriet#9]
Motivasjon: Teodor har tidligere kommet på at han må trekke når han bare har telefon. CLI-et kan ikke brukes fra Telefon. Endepunkt, derimot, funker bra!

Forslag til ny flyt for trekning:

1. Gå til `/olorm/draw/ol` i en nettleser
2. Skjermbilde av resultat
3. Del i `#olorm-intern`, ping personen som ble trukkket (oddmund eller richard)

**Comment by olavm** [comment]
Status: Implementert en slags MVP for olorm. Bør styles litt.
Når dette er på plass må en tilsvarende funksjon opprettes for jals.

**Comment by olavm** [comment]
To-do for draw v1:

- [ ] Gjøre ferdig styling.
- [ ] Lage `jals-draw`.

**Comment by olavm** [comment]
Versjon v1 er ferdig. Man kan gjerne style den mer i fremtiden.

**Comment by teodorlu** [comment]
Nice! Funker bra dette :)
